service: web3-worker

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    WEB3_ACC_PRIVATE_KEY: ${env:WEB3_ACC_PRIVATE_KEY}
    CONTRACT_PROXY: ${env:CONTRACT_PROXY}
    WEB3_INFURA_PROVIDER_URL: ${env:WEB3_INFURA_PROVIDER_URL}
    COMPLETE_TRANSACTION_URL: ${env:COMPLETE_TRANSACTION_URL}

functions:
  # sender:
  #   handler: src/handler.sender
  #   events:
  #     - http:
  #         method: post
  #         path: sender

  senderToBlockchain:
    handler: src/handler.senderToBlockchain
    timeout: 900
    reservedConcurrency: 1
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:445677355183:txQueue.fifo
          batchSize: 1
  
  statusChecker:
    handler: src/handler.statusChecker
    timeout: 900
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:445677355183:pendingTxQueue.fifo
          batchSize: 1
      - schedule:
          rate: rate(5 minutes)

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline
