service: web3-worker

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sender:
    handler: src/handler.sender
    events:
      - http:
          method: post
          path: sender

  receiver:
    handler: src/handler.receiver
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:445677355183:txQueue.fifo
          batchSize: 1

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline
