service: web3-worker

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [txQueue, Arn]
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [pendingTxQueue, Arn]

functions:
  sender:
    handler: src/handler.sender
    timeout: 900
    events:
      - http:
          method: post
          path: sender

  receiver:
    handler: src/handler.receiver
    timeout: 900
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - txQueue
              - Arn
          batchSize: 1
  scheduler:
    handler: src/handler.scheduler
    timeout: 900
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

resources:
  Resources:
    pendingTxQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: pendingTxQueue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
    txQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: txQueue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true

custom:
  esbuild:
    bundle: true
    minify: true

  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2012-11-05"
    endpoint: http://localhost:9324
    region: localhost
    accessKeyId: root
    secretAccessKey: root

plugins:
  - serverless-esbuild
  - serverless-offline-sqs
  - serverless-offline
